### ISSUE TITLE
Sundials27OctaveApp should depend on veclibfort

### ISSUE THREAD

**Issue by schoeps** [octave-app/homebrew-octave-app#1]
`Sundials27OctaveApp` should  not depend on `openblas` but on `veclibfort`. I think that is a migration issue from dpo's repository.

**Comment by apjanke** [comment]
Sorry I didn't see this earlier; I wasn't "Watching" this repo. Added to octave-app-bundler so it goes on the Project board: https://github.com/octave-app/octave-app-bundler/issues/50
