### ISSUE TITLE
"Please run Octave from the /Applications/... folder"

### ISSUE THREAD

**Issue by rpgit12** [octave-app/homebrew-octave-app#2]
Hi - I installed octave-app 4.4 via 'brew tap' & 'brew cask.' However when attempting to start the application using finder, a popup opens with the error message "Please run Octave from the /Applications/Octave-4.4.0.app folder" (which is where the app was installed by brew.)

I am able to successfully run the app from the terminal using this command - so the installed binaries seem to work fine:

`/Applications/Octave-4.4.0.app/Contents/Resources/usr/Cellar/octave-octave-app_4.4.0/4.4.0/libexec/octave/4.4.0/exec/x86_64-apple-darwin17.6.0/octave-gui --gui`

I tried downloading the .dmg from the site as well, but it doesn't work at all - the application quits (crashes?) right away.

Help much appreciated!

**Comment by apjanke** [comment]
Hi! Thanks for helping us test this out.

Could you post the exact `brew tap` and `brew cask` commands you used to install Octave? And where you downloaded the .dmg from? Octave.app does not support `brew cask`, so I think you might be mixing two different installers here.

And how exactly did you try to run the application from Finder?

What OS X version are you running? Could you post the results of running `sw_vers` from the Terminal?

**Comment by apjanke** [comment]
Oh, wait, wait, sorry - you're running it from *this* Cask formula, which is experimental and hasn't been updated to the latest beta yet. So sorry about the confusion! Give me a moment and I'll update this...

**Comment by apjanke** [comment]
Yep, this Cask formula is broken. I will attempt to fix it, but it may take a while.

In the mean time, please:
* Delete `/Applications/Octave-4.4.0.app`, and
* Manually download Octave.app from http://octave-app.org/Download.html and install it by opening the DMG and doing the drag-to-Applications thing.

You may also need to manually delete `/usr/local/Caskroom/octave-app` to get it to work nicely.

Sorry for the inconvenience.

**Comment by apjanke** [comment]
(And if it still crashes after doing those manual deletion steps, please add a comment on https://github.com/octave-app/octave-app/issues/3, where a couple other folks are having similar problems, and include the output of `sw_vers`, and we'll try to fix it.)

**Comment by apjanke** [comment]
I think the Cask formula is fixed now. I'm able to `brew cask install octave-app` and double-click Octave-4.4.0.app to run it with no problems on my 10.13.16 machine.

Closing this out since I think it's fixed. Please re-open if you're still having problems after a `brew update`.

**Comment by s-basant** [comment]
I executed the following command but I got below error.

command: brew cask install octave-app

Error: Cask 'octave-app' is unavailable: No Cask with this name exists.

**Comment by apjanke** [comment]
@s-basant: Did you do a `brew tap octave-app/octave-app-bases` first? That's where that formula lives; it's not in the default Homebrew tap.

**Comment by s-basant** [comment]
thank you. issue got resolved 👍

**Comment by vivekrajiitkgp** [comment]
<img width="1680" alt="screenshot 2019-01-06 at 5 33 32 pm" src="https://user-images.githubusercontent.com/46418288/50735717-3c5fd680-11d9-11e9-89b1-f42505d6d75a.png">

Hi, I just got a new MacBook Pro, and am setting it up. Have installed Xcode, gcc, gfortran, Macports, Homebrew etc. Was just trying to install & run Octave, but am getting the same error again and again: 
Cask 'octave-app' is unavailable: No Cask with this name exists.

I did:
brew tap octave-app/octave-app-bases
brew cask install octave-app

(screenshot of terminal enclosed herein for your kind perusal)

**Comment by apjanke** [comment]
My bad: it's in `octave-app/octave-app`, not `octave-app/octave-app-bases`. Try:

```
brew tap octave-app/octave-app
brew cask install octave-app
```

(`octave-app-bases` contains non-Cask formulae for installing into Homebrew directly. Sorry for the confusion.)

**Comment by vivekrajiitkgp** [comment]
Thank you so much
